# THIS IS A SAMPLE OF THE FILE. Get the full file at the link above.
name: cupertino
description: Creating a Store in Cupertino widgets

environment:
 sdk: "3.5.4"

dependencies:
 flutter:
   sdk: flutter

 cupertino_icons: ^1.0.8
 intl: ^0.19.0
 provider: ^6.1.2
 shrine_images: ^2.0.2
 scoped_model: ^2.0.0

dev_dependencies:
 pedantic: ^1.4.0

flutter:
 
 assets:
   - packages/shrine_images/0-0.jpg
# THIS IS A SAMPLE OF THE FILE. Get the full file at the link above.